spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bugkeeper
    username: ${DB_USER:bugkeeper}
    password: ${DB_PASS}
google:
  translate:
    api_key: ${API_KEY}
jwt:
  secret: ${ENCODED_SECRET} # base64-encoded key
