spring:
  application:
    name: BugKeeper
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
google:
  translate:
    url: https://translation.googleapis.com
jwt:
  expiration-ms: 3600000
