name: CI - Test, Coverage & Sonar Analysis

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Verify (Test + Coverage + Analysis)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-v1-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-v1-${{ runner.os }}-
            gradle-cache-v1-

      - name: Ensure Gradle wrapper exists
        run: test -f ./gradlew || { echo "Missing gradlew"; exit 1; }

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport --no-daemon

      - name: Upload JaCoCo HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html/

      - name: Run Sonar with Gradle
        run: ./gradlew sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} --no-daemon --warning-mode all

      - name: Run coverage check
        run: ./gradlew check --no-daemon
